# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d963ae093a924e863ba43fbd299b0e0c5345c664ddbdfff77c60ab9f080e71fd1544f931403a1bcea5fcc32970fa3a5e23e0dfb909404955739d4ef0239cf853

test:
  secret_key_base: ff24e21a8ac48a446420f9fef73ec345751dc81a524ea2aa83adec0b35ab4416ba9b41771076de31c2eb1f455cd6b91b8cfd3dd60ec27059879bb973d258c8da

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
